// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCId0SXTIQ-uqzgvDgcJTfyr2JfxEL2LQY',
    appId: '1:220524887706:web:12b797b21d968eaa9fe923',
    messagingSenderId: '220524887706',
    projectId: 'spare-waka',
    authDomain: 'spare-waka.firebaseapp.com',
    storageBucket: 'spare-waka.firebasestorage.app',
    measurementId: 'G-JBW5NLFZR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgvp6HBQ-k1WkShLS2QWijMice9MLsmR8',
    appId: '1:220524887706:android:8e7d5f9692995e729fe923',
    messagingSenderId: '220524887706',
    projectId: 'spare-waka',
    storageBucket: 'spare-waka.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBubDJD8NFieUeGKC9TBiQZ4bz4ph0uHvo',
    appId: '1:220524887706:ios:44c15b21a2d1f3829fe923',
    messagingSenderId: '220524887706',
    projectId: 'spare-waka',
    storageBucket: 'spare-waka.firebasestorage.app',
    iosBundleId: 'com.example.spareWaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBubDJD8NFieUeGKC9TBiQZ4bz4ph0uHvo',
    appId: '1:220524887706:ios:44c15b21a2d1f3829fe923',
    messagingSenderId: '220524887706',
    projectId: 'spare-waka',
    storageBucket: 'spare-waka.firebasestorage.app',
    iosBundleId: 'com.example.spareWaka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCId0SXTIQ-uqzgvDgcJTfyr2JfxEL2LQY',
    appId: '1:220524887706:web:8afb8b434c06ec3d9fe923',
    messagingSenderId: '220524887706',
    projectId: 'spare-waka',
    authDomain: 'spare-waka.firebaseapp.com',
    storageBucket: 'spare-waka.firebasestorage.app',
    measurementId: 'G-RSBC7H18PX',
  );
}
